version: '3.8'

services:
  backend:
    build:
      context: ../backend
      dockerfile: ../docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Shanghai
      - HOST=0.0.0.0
      - PORT=8000
      - USE_MYSQL=false
      - DISPLAY=:99
      - PLAYWRIGHT_BROWSERS_PATH=/home/playwright/.cache/ms-playwright
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-}
    shm_size: '2gb'
    volumes:
      - ../backend:/app
      - ./data:/app/data
    networks:
      - autotest-network

  frontend:
    build:
      context: ../frontend
      dockerfile: ../docker/Dockerfile.frontend
      args:
        VITE_API_BASE_URL: http://localhost:8000
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Shanghai
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - autotest-network

networks:
  autotest-network:
    driver: bridge

volumes:
  data: 