version: '3.8'

services:
  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - TZ=Asia/Shanghai
      - HOST=0.0.0.0
      - PORT=8000
      - USE_MYSQL=false
      - DISPLAY=:99
      - DOCKER_ENV=true
      - DATA_DIR=/app/data
      - DB_NAME=autotest.db
    shm_size: '2gb'
    volumes:
      - ../backend:/app
      - ./data:/app/data
    networks:
      - autotest-network

  frontend:
    build:
      context: ../
      dockerfile: docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    env_file:
      - config.env
    depends_on:
      - backend
    networks:
      - autotest-network

networks:
  autotest-network:
    driver: bridge

volumes:
  data: 